<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Error</title>
   <link rel="stylesheet" href="/css/candidates.css">
</head>
<body>
   <div class="container flex flex-col align-center">
     <div class="error-container">
       <h1>Error</h1>

       <div class="error-message">
         ${error}
       </div>
     </div>

     <a class="back flex align-center" href="/">back to main</a>
   </div>
</body>
</html>